cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ap-south-1
    stack:
      auto: false

application:
  bucket:
    name: moviesmicroservice


server:
  port: 8080
